export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const PROJECT_TABS = 'PROJECT_TABS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const JOIN_PROJECT = 'JOIN_PROJECT';
export const PROJECT_CONTENT = 'PROJECT_CONTENT';

// YOUTUBE LINK
export const PROJECT_CONTENT_LINK = 'PROJECT_CONTENT_LINK';
export const ADD_YOUTUBE_LINK = 'ADD_YOUTUBE_LINK';
export const DELETE_YOUTUBE_LINK = 'DELETE_YOUTUBE_LINK';